# CI de Nível 01 - Disparo manual a partir de 1 clique

name: "Execução Manual"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando dependências do projeto
        run: npm install

      - name: Testes E2E (end-to-end)
        run: npm run headless:mode:all

      - uses: actions/upload-artifact@v4
        with: 
          name: relatorio-tests
          path: ./cypress/reports/html
